WIP: improve hooks implementation (#28)
<!--
Thanks for your interest in the project. Bugs filed and PRs submitted are appreciated!

Please make sure that you are familiar with and follow the Code of Conduct for
this project (found in the CODE_OF_CONDUCT.md file).

Also, please make sure you're familiar with and follow the instructions in the
contributing guidelines (found in the CONTRIBUTING.md file).

If you're new to contributing to open source projects, you might find this free
video course helpful: http://kcd.im/pull-request

Please fill out the information below to expedite the review and (hopefully)
merge of your pull request!
-->

<!-- What changes are being made? (What feature/bug is being fixed here?) -->
**What**:
- memoized all functions (setOn, setOff, toggle, getTogglerProps, getInputTogglerProps, getElementTogglerProps)
- reverted tests to before hooks
- removed exception when changing from controlled to uncontrolled, but added warning
<!-- Why are these changes necessary? -->
**Why**:
- To prevent unnecessary rerenders of child components, the functions provided by react-toggled should only change when needed.
- The test was reverted as it only failed if the functions of react-toggled are not memoized. I think this could be considered a bug and therefore the previous tests were more accurate.
- When the user changes react-toggled from controlled to uncontrolled a warning could be better than an exception thrown by React (order of hooks). 
<!-- How were these changes implemented? -->
**How**:
- all functions are wrapped in useCallback with all needed parameters as second argument
- tests were reverted to master
- when the env is not production it is tested via a useRef whether the hook is changed from controlled to uncontrolled or vice versa. If this is true a warning is printed.
<!-- Have you done all of these things?  -->
**Checklist**:
<!-- add "N/A" to the end of each line that's irrelevant to your changes -->
<!-- to check an item, place an "x" in the box like so: "- [x] Documentation" -->
- [ ] Documentation N/A
- [ ] Tests
- [ ] Ready to be merged <!-- In your opinion, is this ready to be merged as soon as it's reviewed? -->
- [x] Added myself to contributors table <!-- this is optional, see the contributing guidelines for instructions -->

<!-- feel free to add additional comments -->
**Validate**: I cannot get npm run validate to work on my Windows machine. It fails during build:
```
[preact.umd.min] .\\node_modules\\cross-env\\dist\\bin\\cross-env.js BUILD_ROLLUP=true BUILD_FORMAT=umd BUILD_MINIFY=true NODE_ENV=production BUILD_PREACT=true BUILD_NODE=false BUILD_REACT_NATIVE=false .\\node_modules\\rollup\\bin\\rollup --config .\\node_modules\\kcd-scripts\\dist\\config\\rollup.config.js --sourcemap exited with code 0
path.js:28
    throw new TypeError('Path must be a string. Received ' + inspect(path));
    ^

TypeError: Path must be a string. Received undefined
```
**Warning**: I am also not sure how you want to handle the warning. I tried to copy the way React handles controlled to uncontrolled input warnings.